"""Discoverable configuration key registry for CLI/help/docs parity."""

from dataclasses import dataclass


@dataclass(frozen=True)
class ConfigKeySpec:
    """Machine-readable specification for a discoverable config key."""

    key: str
    value_type: str
    default: object | None
    description: str
    required: bool = False
    example_value: object | None = None


# Runtime-only Config dataclass fields; not user-configurable keys.
RUNTIME_ONLY_CONFIG_FIELDS = {
    "project_dir",
    "db_path_value",
    "source_map",
    "user_config_file",
    "user_config_active",
    "local_override_path",
    "local_overrides_active",
    "provider_cwd",
    "docker_workdir",
}

# Extra accepted config roots that are not direct Config dataclass fields.
NON_CONFIG_ROOT_KEYS = {
    "defaults",
    "claude_args",
    "db_path",
}


CONFIG_KEY_REGISTRY: tuple[ConfigKeySpec, ...] = (
    ConfigKeySpec(
        "advance_create_reviews",
        "bool",
        True,
        "Auto-create review tasks in lifecycle flows when review gating still requires them; manual attention is required instead when review creation is disabled.",
    ),
    ConfigKeySpec(
        "advance_off_topic_verify_unblock",
        "bool",
        False,
        "Allow lifecycle to clear a verify-only blocked review through the off-topic verify classifier; when false, the verify-only blocker remains conservative and stays blocking.",
    ),
    ConfigKeySpec(
        "advance_create_plan_reviews",
        "bool",
        True,
        "Auto-create plan_review tasks for completed non-held plans; manual attention is required instead when plan-review creation is disabled.",
    ),
    ConfigKeySpec("advance_mode", "str", "default", "Mode selector for `gza advance` behavior."),
    ConfigKeySpec(
        "require_review_before_merge",
        "bool",
        True,
        "Require a valid current review before lifecycle auto-merge.",
    ),
    ConfigKeySpec(
        "require_plan_review_before_implement",
        "bool",
        True,
        "Require a current approved plan_review before lifecycle automation materializes implementation work from a plan.",
    ),
    ConfigKeySpec(
        "pr_integration",
        "bool",
        True,
        "Enable GitHub PR discovery, commenting, and auto-create flows. Set false to skip all gh-backed PR operations for the project.",
    ),
    ConfigKeySpec("branch_mode", "str", "multi", "Git branch mode: `single` or `multi`."),
    ConfigKeySpec("branch_strategy", "str | object", "project_date_slug", "Branch naming strategy preset or object."),
    ConfigKeySpec("branch_strategy.default_type", "str", "feature", "Default type token for branch strategy patterns."),
    ConfigKeySpec("branch_strategy.pattern", "str", "{project}/{date}-{slug}", "Branch naming format pattern."),
    ConfigKeySpec("chat_text_display_length", "int", 0, "Chat output truncation length (0 = unlimited)."),
    ConfigKeySpec("claude.args", "list[str]", ["--allowedTools", "Read", "Write", "Edit", "Glob", "Grep", "Bash"], "Claude CLI arguments."),
    ConfigKeySpec("claude.fetch_auth_token_from_keychain", "bool", False, "Fetch Claude auth token from macOS keychain for Docker."),
    ConfigKeySpec("claude_args", "list[str]", None, "Deprecated legacy alias for `claude.args`."),
    ConfigKeySpec("cleanup_days", "int", 30, "Default retention window for `gza clean`."),
    ConfigKeySpec(
        "quiet_period_seconds",
        "int",
        300,
        "Seconds a newly created task stays in the Quiet lane of `gza queue` / `gza next` before rejoining normal pending display order; current releases still do not change worker pickup eligibility, and `0` disables the quiet lane.",
    ),
    ConfigKeySpec("colors.*", "str", None, "Ad-hoc color override map keyed by output field."),
    ConfigKeySpec("defaults.max_steps", "int", 50, "Default step budget for task execution."),
    ConfigKeySpec("defaults.max_turns", "int", 50, "Deprecated legacy alias for defaults.max_steps."),
    ConfigKeySpec("defaults.model", "str", "", "Legacy global default model fallback."),
    ConfigKeySpec("defaults.reasoning_effort", "str", "", "Legacy global default reasoning effort fallback (Codex)."),
    ConfigKeySpec("docker_image", "str", "{project_name}-gza", "Docker image used for task execution."),
    ConfigKeySpec(
        "docker_setup_command",
        "str",
        "",
        "Pre-warm command run synchronously inside Docker before provider CLI starts.",
    ),
    ConfigKeySpec("docker_volumes", "list[str]", [], "Extra Docker volume mounts (`source:dest[:mode]`)."),
    ConfigKeySpec("db_path", "str", ".gza/gza.db", "SQLite database path."),
    ConfigKeySpec(
        "docker_startup_timeout",
        "int",
        60,
        "Seconds to wait for Docker daemon startup or wake-up before treating Docker as unavailable.",
    ),
    ConfigKeySpec("inner_verify_command", "str", "", "Optional fast inner-loop verification command for code tasks; `verify_command` remains the required final gate."),
    ConfigKeySpec("interactive_worktree_dir", "str", "", "Base path for interactive worktree operations."),
    ConfigKeySpec("iterate_max_iterations", "int", 3, "Default iteration budget for `gza iterate`."),
    ConfigKeySpec("learnings_interval", "int", 5, "Auto-regenerate learnings every N completed tasks (0 disables)."),
    ConfigKeySpec("learnings_max_items", "int", 50, "Max number of items retained in `.gza/learnings.md`."),
    ConfigKeySpec("learnings_window", "int", 25, "Window size used when regenerating learnings."),
    ConfigKeySpec("log_dir", "str", ".gza/logs", "Directory for task and worker logs."),
    ConfigKeySpec(
        "max_resume_attempts",
        "int",
        1,
        "Shared automatic failed-task recovery toggle: 0 disables; any positive value enables the fixed bounded resume/retry policy used by advance, iterate improve recovery, and watch.",
    ),
    ConfigKeySpec("max_review_cycles", "int", 3, "Cap for review/improve loops in lifecycle automation."),
    ConfigKeySpec("max_plan_review_cycles", "int", 2, "Cap for plan_review/plan_improve loops in lifecycle automation."),
    ConfigKeySpec(
        "max_failed_plan_review_retries",
        "int",
        3,
        "Max failed plan_review attempts for one plan source before lifecycle parks it as needs_attention instead of auto-spawning another review; 0 escalates after the first failure.",
    ),
    ConfigKeySpec("max_noop_improve_cycles", "int", 1, "Cap for consecutive no-op improves before lifecycle automation stops for discussion."),
    ConfigKeySpec("max_plan_slices", "int | null", None, "Optional cap on auto-materialized implementation slices from one approved plan review."),
    ConfigKeySpec(
        "plan_slice_target_timeout_minutes",
        "int | null",
        "code_task_diff_timeout_cap_minutes or 45",
        "Optional reviewer budget target for one implementation slice; when unset it derives from code-task timeout sizing.",
        example_value=45,
    ),
    ConfigKeySpec("max_failed_closing_review_retries", "int", 3, "Max consecutive failed closing-review attempts before the lineage is parked as needs_attention; 0 escalates on first failure."),
    ConfigKeySpec(
        "max_concurrent",
        "int",
        "effective watch batch or 5",
        "Hard global ceiling on concurrently running task-executing processes across all commands. Explicit `max_concurrent` wins; when it is unset, `gza watch` derives its runtime cap from the effective watch batch (including `--batch`), while other commands keep the loaded fallback (`watch.batch` if configured, otherwise `5`).",
        example_value=5,
    ),
    ConfigKeySpec("max_steps", "int", 50, "Global default step budget."),
    ConfigKeySpec("max_turns", "int", 50, "Deprecated global alias for `max_steps`."),
    ConfigKeySpec("main_checkout_isolate", "bool", False, "Stage watch-time merges in a detached integration checkout before advancing the real default branch on success."),
    ConfigKeySpec("merge_squash_threshold", "int", 0, "Auto-squash threshold for merge operations."),
    ConfigKeySpec("model", "str", "", "Legacy global model fallback."),
    ConfigKeySpec(
        "no_color",
        "bool",
        False,
        "Disable all Rich color/theming on TTYs; `NO_COLOR` still disables color regardless of this setting.",
    ),
    ConfigKeySpec("reasoning_effort", "str", "", "Legacy global reasoning effort fallback (Codex)."),
    ConfigKeySpec(
        "project_id",
        "str",
        "derived from project path/name",
        "Stable project identity used for DB row scoping.",
    ),
    ConfigKeySpec("project_name", "str", None, "Project identifier used for naming and defaults.", required=True),
    ConfigKeySpec("project_prefix", "str", "derived from project_name", "Task-ID prefix (1-12 lowercase alphanumeric chars)."),
    ConfigKeySpec("provider", "str", "claude", "Default provider when task-specific routing is absent."),
    ConfigKeySpec("providers.*.model", "str", None, "Provider-scoped default model."),
    ConfigKeySpec("providers.*.reasoning_effort", "str", None, "Provider-scoped default reasoning effort (Codex)."),
    ConfigKeySpec("providers.*.task_types.*.max_steps", "int", None, "Provider/task-type step budget override."),
    ConfigKeySpec("providers.*.task_types.*.max_turns", "int", None, "Deprecated provider/task-type alias for max_steps."),
    ConfigKeySpec("providers.*.task_types.*.model", "str", None, "Provider/task-type model override."),
    ConfigKeySpec("providers.*.task_types.*.reasoning_effort", "str", None, "Provider/task-type reasoning effort override (Codex)."),
    ConfigKeySpec("providers.*.task_types.*.timeout_minutes", "int", None, "Provider/task-type runtime budget override."),
    ConfigKeySpec("code_task_diff_timeout_medium_threshold", "int", 400, "Changed-line threshold where code tasks can receive the medium scaled timeout."),
    ConfigKeySpec("code_task_diff_timeout_large_threshold", "int", 1200, "Changed-line threshold where code tasks can receive the large scaled timeout."),
    ConfigKeySpec("code_task_diff_timeout_medium_minutes", "int", 30, "Scaled timeout applied to code tasks at or above the medium diff threshold."),
    ConfigKeySpec("code_task_diff_timeout_large_minutes", "int", 45, "Scaled timeout applied to code tasks at or above the large diff threshold."),
    ConfigKeySpec("code_task_diff_timeout_cap_minutes", "int", 45, "Hard maximum runtime budget for code tasks after base timeout resolution and diff-size scaling."),
    ConfigKeySpec("review_context_file_limit", "int", 12, "Max changed files included in large review context excerpts."),
    ConfigKeySpec("autonomous_verify_timeout_seconds", "int", 120, "Timeout in seconds for lifecycle/automation-initiated verify_command runs."),
    ConfigKeySpec(
        "review_verify_timeout_grace_seconds",
        "float",
        5,
        "Grace period in seconds after SIGTERM before autonomous review verification escalates to SIGKILL.",
    ),
    ConfigKeySpec(
        "main_integration_verify_red_ttl_minutes",
        "int",
        30,
        "Maximum age of a failed/unavailable local-target integration verify checkpoint before automation reruns it even when the tree fingerprint is unchanged.",
    ),
    ConfigKeySpec("recommend_rebase_behind_commits", "int", 1, "Deprecated compatibility key; accepted but ignored."),
    ConfigKeySpec("review_diff_medium_threshold", "int", 2000, "Medium diff threshold for review prompt shaping."),
    ConfigKeySpec("review_diff_small_threshold", "int", 500, "Small diff threshold for full inline review diffs."),
    ConfigKeySpec("task_providers.*", "str", None, "Task-type to provider routing override."),
    ConfigKeySpec("task_types.*.max_steps", "int", None, "Legacy per-task-type step budget override."),
    ConfigKeySpec("task_types.*.max_turns", "int", None, "Deprecated legacy per-task-type alias for max_steps."),
    ConfigKeySpec("task_types.*.model", "str", None, "Legacy per-task-type model override."),
    ConfigKeySpec("task_types.*.reasoning_effort", "str", None, "Legacy per-task-type reasoning effort override (Codex)."),
    ConfigKeySpec("task_types.*.timeout_minutes", "int", None, "Legacy per-task-type runtime budget override."),
    ConfigKeySpec("tasks_file", "str", "tasks.yaml", "Legacy task list file path."),
    ConfigKeySpec("theme", "str", "minimal", "Built-in color theme name."),
    ConfigKeySpec("timeout_minutes", "int", 10, "Max runtime minutes before a task times out."),
    ConfigKeySpec("tmux.auto_accept_timeout", "float", 10.0, "Seconds of quiescence before auto-accept in tmux."),
    ConfigKeySpec("tmux.detach_grace", "float", 5.0, "Grace period after manual detach before auto-accept resumes."),
    ConfigKeySpec("tmux.enabled", "bool", False, "Enable tmux-backed background sessions."),
    ConfigKeySpec("tmux.max_idle_timeout", "float", 300.0, "Max idle seconds before tmux session is considered stuck."),
    ConfigKeySpec("tmux.terminal_size", "list[int]", [200, 50], "Tmux terminal dimensions `[cols, rows]`."),
    ConfigKeySpec("use_docker", "bool", True, "Run providers in Docker."),
    ConfigKeySpec(
        "enforce_project_scope",
        "bool",
        True,
        "Enforce repo-subtree write boundaries at commit time; `cross-project` tagged tasks are exempt.",
    ),
    ConfigKeySpec("verify_command", "str", "", "Project verification command used before completion and during autonomous review cycles."),
    ConfigKeySpec("watch.batch", "int", 2, "Default concurrent worker target for `gza watch`."),
    ConfigKeySpec("watch.failure_backoff_initial", "int", 60, "Initial cooldown after a non-auto-resumable watch failure."),
    ConfigKeySpec("watch.failure_backoff_max", "int", 3600, "Maximum cooldown after consecutive non-auto-resumable watch failures."),
    ConfigKeySpec(
        "watch.transient_recovery_backoff_max",
        "int",
        1800,
        "Maximum cooldown for transient watch recovery retries after the bounded schedule ramps up.",
    ),
    ConfigKeySpec("watch.failure_halt_after", "int | null", 10, "Exit `gza watch` after this many consecutive non-auto-resumable failures."),
    ConfigKeySpec("watch.no_progress_cycles", "int", 3, "Repeated unchanged watch-action cycles before the subject is parked for manual attention."),
    ConfigKeySpec("watch.dispatch_start_timeout", "int", 2, "Bounded seconds `gza watch` waits for selected work to reach a live running state before treating the dispatch as undispatched and moving on."),
    ConfigKeySpec("watch.max_idle", "int | null", None, "Idle timeout seconds for `gza watch` loop exit."),
    ConfigKeySpec("watch.no_activity_timeout", "int", 60, "Seconds before watch reconciliation marks a silent registered worker for a pending or in-progress task `NO_ACTIVITY`."),
    ConfigKeySpec("watch.max_iterations", "int", 10, "Default review/improve loop cap in `gza watch`."),
    ConfigKeySpec("watch.poll", "int", 300, "Polling interval seconds for `gza watch`."),
    ConfigKeySpec(
        "watch.recovery_slots",
        "int",
        1,
        "Slots per `gza watch` pass reserved for worker-consuming failed-task recovery before pending pickup; `0` is pending-only.",
    ),
    ConfigKeySpec(
        "watch.restart_failed_batch",
        "int",
        1,
        "Deprecated alias for `watch.recovery_slots`.",
    ),
    ConfigKeySpec("work_count", "int", 1, "Default task count for each `gza work` run."),
    ConfigKeySpec("worktree_dir", "str", "/tmp/gza-worktrees", "Base directory for git worktrees."),
)
